package com.oxygen.weather.core.provider.openmeteo

data class OpenMeteoForecastResponse(
    val latitude: Double,
    val longitude: Double,
    val generationTimeMs: Double,
    val utcOffsetSeconds: Int,
    val timezone: String,
    val timezoneAbbreviation: String,
    val elevation: Double?,
    val currentUnits: Map<String, String>,
    val current: OpenMeteoCurrentForecast,
    val hourlyUnits: Map<String, String>,
    val hourly: OpenMeteoHourlyForecast,
    val dailyUnits: Map<String, String>,
    val daily: OpenMeteoDailyForecast,
)

data class OpenMeteoCurrentForecast(
    val time: String,
    val interval: Int?,
    val temperature2m: Double?,
    val relativeHumidity2m: Int?,
    val apparentTemperature: Double?,
    val isDay: Int?,
    val precipitation: Double?,
    val rain: Double?,
    val showers: Double?,
    val snowfall: Double?,
    val weatherCode: Int?,
    val cloudCover: Int?,
    val pressureMsl: Double?,
    val surfacePressure: Double?,
    val windSpeed10m: Double?,
    val windDirection10m: Int?,
    val windGusts10m: Double?,
)

data class OpenMeteoHourlyForecast(
    val time: List<String>,
    val temperature2m: List<Double?>,
    val relativeHumidity2m: List<Int?>,
    val dewPoint2m: List<Double?>,
    val apparentTemperature: List<Double?>,
    val precipitationProbability: List<Int?>,
    val precipitation: List<Double?>,
    val rain: List<Double?>,
    val showers: List<Double?>,
    val snowfall: List<Double?>,
    val weatherCode: List<Int?>,
    val pressureMsl: List<Double?>,
    val surfacePressure: List<Double?>,
    val cloudCover: List<Int?>,
    val visibility: List<Double?>,
    val uvIndex: List<Double?>,
    val isDay: List<Int?>,
    val windSpeed10m: List<Double?>,
    val windDirection10m: List<Int?>,
    val windGusts10m: List<Double?>,
)

data class OpenMeteoDailyForecast(
    val time: List<String>,
    val weatherCode: List<Int?>,
    val temperature2mMax: List<Double?>,
    val temperature2mMin: List<Double?>,
    val apparentTemperatureMax: List<Double?>,
    val apparentTemperatureMin: List<Double?>,
    val uvIndexMax: List<Double?>,
    val sunrise: List<String?>,
    val sunset: List<String?>,
    val daylightDuration: List<Double?>,
    val rainSum: List<Double?>,
    val showersSum: List<Double?>,
    val snowfallSum: List<Double?>,
    val precipitationSum: List<Double?>,
    val precipitationHours: List<Double?>,
    val precipitationProbabilityMax: List<Int?>,
    val windSpeed10mMax: List<Double?>,
    val windGusts10mMax: List<Double?>,
    val windDirection10mDominant: List<Int?>,
)
